/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SampleModalFromServiceTypeRouteImport } from './routes/sampleModal/$from/$serviceType'
import { Route as SampleModalIndexRouteImport } from './routes/sampleModal/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleModalIndexRoute = SampleModalIndexRouteImport.update({
  id: '/sampleModal/',
  path: '/sampleModal/',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleModalFromServiceTypeRoute =
  SampleModalFromServiceTypeRouteImport.update({
    id: '/sampleModal/$from/$serviceType',
    path: '/sampleModal/$from/$serviceType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sampleModal/': typeof SampleModalIndexRoute
  '/sampleModal/$from/$serviceType': typeof SampleModalFromServiceTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sampleModal': typeof SampleModalIndexRoute
  '/sampleModal/$from/$serviceType': typeof SampleModalFromServiceTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sampleModal/': typeof SampleModalIndexRoute
  '/sampleModal/$from/$serviceType': typeof SampleModalFromServiceTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sampleModal/' | '/sampleModal/$from/$serviceType'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sampleModal' | '/sampleModal/$from/$serviceType'
  id: '__root__' | '/' | '/sampleModal/' | '/sampleModal/$from/$serviceType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SampleModalIndexRoute: typeof SampleModalIndexRoute
  SampleModalFromServiceTypeRoute: typeof SampleModalFromServiceTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sampleModal/': {
      id: '/sampleModal/'
      path: '/sampleModal'
      fullPath: '/sampleModal/'
      preLoaderRoute: typeof SampleModalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sampleModal/$from/$serviceType': {
      id: '/sampleModal/$from/$serviceType'
      path: '/sampleModal/$from/$serviceType'
      fullPath: '/sampleModal/$from/$serviceType'
      preLoaderRoute: typeof SampleModalFromServiceTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SampleModalIndexRoute: SampleModalIndexRoute,
  SampleModalFromServiceTypeRoute: SampleModalFromServiceTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
